global:
  smtp_smarthost: mailna.insight.com:25
  smtp_from: pm_analytics@insight.com
  smtp_require_tls: false

route:
  group_by: ['service']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 5m
  receiver: default.receiver
  routes:
  - match:
      service: Platform
    # receiver: Platform.receiver
    # continue: true
receivers:
- name: default.receiver
  email_configs:
    - to: rduran@insight.com,svc_BIEmailBot@insight.com
      headers:
        subject: "105 -Container Down Alert! Service {{ .Alerts.Firing.Labels.alertname }} is unavailable."
# - name: example.receiver
#   email_configs:
#     - to: rduran@insight.com,svc_BIEmailBot@insight.com .Alerts.Firing .Annotations.description
