route:
  group_by: [Alertname]
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: rduran@insight.com
    from: pm_analytics@insight.com
    smarthost: mailna.insight.com:25
    auth_username: "pm_analytics@insight.com"
    auth_identity: "pm_analytics@insight.com"
    auth_password: "**********************"