groups:
- name: ./rules.conf
  rules:
  # service availability alert
  - alert: service_down
    expr: up == 0
    labels:
      service: Platform
      severity: major
      correlate: service_up,service_down
    annotations:
      description: Service {{ $labels.instance }} is unavailable.
      value: DOWN ({{ $value }})

  # service availability alert
  - alert: worker10_down
    expr: count(rate(container_last_seen{job="cadvisor", name="bi-airflow_worker_10"}[1m])) != 1
    labels:
      service: Platform
      severity: major
    annotations:
      description: Service bi-airflow_worker_10 is unavailable.
      value: DOWN (bi-airflow_worker_10)