groups:
- name: ./rules.conf
  rules:

  - alert: service_down
    expr: up == 0
    labels:
      service: Platform
      severity: major
      correlate: service_up,service_down
    annotations:
      description: Service {{ $labels.instance }} is unavailable.
      value: DOWN ({{ $value }})

  - alert: worker10_down
    expr: absent(container_last_seen{job="cadvisor", name="bi-airflow_worker_10"}) == 1
    labels:
      service: Platform
      severity: major
    annotations:
      description: Service bi-airflow_worker_10 is unavailable.
      value: DOWN (bi-airflow_worker_10)

  - alert: bi-airflow_scheduler_1
    expr: absent(container_last_seen{job="cadvisor", name="bi-airflow_scheduler_1"}) == 1
    labels:
      service: Platform
      severity: major
    annotations:
      description: Service bi-airflow_scheduler_1 is unavailable.
      value: DOWN (bi-airflow_scheduler_1)

  - alert: bi-airflow_postgres_1
    expr: absent(container_last_seen{job="cadvisor", name="bi-airflow_postgres_1"}) == 1
    labels:
      service: Platform
      severity: major
    annotations:
      description: Service bi-airflow_postgres_1 is unavailable.
      value: DOWN (bi-airflow_postgres_1)

  - alert: bi-airflow_redis_1
    expr: absent(container_last_seen{job="cadvisor", name="bi-airflow_redis_1"}) == 1
    labels:
      service: Platform
      severity: major
    annotations:
      description: Service bi-airflow_redis_1 is unavailable.
      value: DOWN (bi-airflow_redis_1)

  - alert: bi-airflow_webserver_1
    expr: absent(container_last_seen{job="cadvisor", name="bi-airflow_webserver_1"}) == 1
    labels:
      service: Platform
      severity: major
    annotations:
      description: Service bi-airflow_webserver_1 is unavailable.
      value: DOWN (bi-airflow_webserver_1)