groups:
- name: ./rules.conf
  rules:

  - alert: service_down
    expr: up == 0
    labels:
      service: Platform
      severity: major
      correlate: service_up,service_down
    annotations:
      description: Service {{ $labels.instance }} in PROD is unavailable.
      value: DOWN ({{ $value }})

  - alert: AzureETEndpoint
    expr: absent(container_last_seen{job="cadvisor", name="AzureETEndpoint"}) == 1
    labels:
      service: Platform
      severity: major
    annotations:
      description: Service AzureETEndpoint is unavailable in PROD.
      value: DOWN (AzureETEndpoint)

  - alert: tokenbi
    expr: absent(container_last_seen{job="cadvisor", name="tokenbi"}) == 1
    labels:
      service: Platform
      severity: major
    annotations:
      description: Service bi-airflow_scheduler_1 is unavailable in PROD.
      value: DOWN (tokenbi)