# prometheus global config
global:
  scrape_interval:     15s
  evaluation_interval: 15s
  # scrape_timeout is set to the global default (10s).
  external_labels:
    monitor: codelab
    environment: Dev
    service: Prometheus
    region: USA
    dc: us-west-1

alerting:
  alertmanagers:
  - static_configs:
    - targets: ["172.25.10.224:9093"]

rule_files:
  - "prometheus.rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "cadvisor"
    scrape_interval: 5s
    static_configs:
      - targets: ["172.25.10.224:8082"]
  - job_name: "node-exporter"
    scrape_interval: 5s
    static_configs:
    - targets: ["172.25.10.224:9100"]
