scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "cadvisor"
    scrape_interval: 5s
    static_configs:
      - targets: ["172.25.10.223:8082"]
  - job_name: "node-exporter"
    scrape_interval: 5s
    static_configs:
    - targets: ["172.25.10.223:9100"]

alerting:
  alertmanagers:
  - static_configs:
  - targets: ["172.25.10.223:9093"]
  
rule_files:
  - 'prometheus.rules.yml'