global:
  scrape_interval:     120s # By default, scrape targets every 15 seconds.
  evaluation_interval: 120s # By default, scrape targets every 15 seconds.
  external_labels:
      monitor: 'my-project'

rule_files:
  # - "alert.rules"
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 120s
    static_configs:
         - targets: ['localhost:9090','172.25.10.223:8082','172.25.10.223:9100']
        #  ['localhost:9090','cadvisor:8080','node-exporter:9100', 'nginx-exporter:9113']